name: diamond_node_slider
description: The node is a diamond slider, which can achieve two effects with transition value and node value.
version: 0.0.1+5
homepage: https://github.com/dushiling
repository: https://github.com/dushiling/diamond_node_slider

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true



